# Generated by Django 4.1.7 on 2023-03-20 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_remove_customuser_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.IntegerField(default=36663222),
            preserve_default=False,
        ),
    ]
