# Generated by Django 4.1.7 on 2023-03-21 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_customuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='location',
            field=models.CharField(choices=[('m', 'Manama'), ('j', 'Jufair'), ('r', 'Riffa'), ('h', 'Hidd'), ('u', 'muharag'), ('i', 'Isa-Town')], default='m', max_length=50),
        ),
    ]
