# Generated by Django 4.1.7 on 2023-03-19 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_userprofile'),
        ('main_app', '0004_alter_events_location'),
    ]

    operations = [
    ]
